export const celebratoryTexts = [
  "Let’s celebrate with some confetti!",
  "It’s your special day — let the fun begin!",
  "Here’s to an amazing year ahead! 🎉",
  "The world is a better place with you in it. Let’s make this year unforgettable!",
  "Happy birthday to the one who deserves all the happiness in the world!",
  "Khushiyan ho, dosti ho, aur saare sapne sach ho!",
  "Birthday girl/boy ki duniya ho, jahan sirf khushiyan ho!",
  "Let the good times roll and the cake flow! Happy Birthday!",
  "Aaj ka din hai celebration ka, toh ho jao ready to party!",
  "Cheers to another year of happiness and fun!",
  "Aapka birthday hai, toh duniya ko pata chale!",
  "Jahan bhi tum jayein, sabke chehre pe muskaan ho!",
  "Time to turn the music up and enjoy the day. Let’s celebrate!",
  "Dil se wish karte hain, zindagi ki saari khushiyan tumse milne aaye!",
  "May the year ahead bring you all that you wish for and more!",
  "It’s time to let your hair down and party — you deserve it!",
  "Aaj ka din hai sirf aapka, celebrate it in style!",
  "It’s time to party! The day is all yours!",
  "Yeh saal ho tumhara, sabse best saal. Happy Birthday!",
  "Aaj ka din hai celebration ka, aur tum ho uska reason!",
  "The universe is aligned for you today, so go ahead and make the most of it!",
  "The world is yours today, let’s celebrate and enjoy every moment!",
  "Birthday ho, toh cake aur dosti sab honi chahiye!",
  "Time for fun, laughter, and good vibes today!",
  "Happiness is a gift and today, it's all yours!",
  "Aapki life ho full of success, adventure, and joy. Enjoy the journey!",
  "Celebrate yourself, you deserve all the best!",
  "Duniya ke har pal me khushiyan ho, tumhari har ek wishes poori ho!",
  "Cheers to another year of success, adventure, and love. Happy Birthday!",
  "Have a blast today, you deserve it all!"
];