export const funElements = [
    "Pata hai? Humare birthday par cake ka tradition ancient Greece se aaya tha! 🎂",
    "Fun Fact: Kuch log maanta hai ki jo hum birthday pe karte hain, wahi humare saal ko set karta hai!",
    "&lsquo;Happy Birthday&rsquo; song duniya ka sabse zyada gaya gaya song hai — kitna famous hai na!",
    "Kehte hain, birthday pe jitni candles hoti hain, utni umra hoti hai! 🎉",
    "Did you know? India mein birthday par ek purani tradition hai, cake cutting sabke saath enjoy karna!",
    "Aapne suna hai? Duniya ka sabse bada birthday cake 100 feet lamba tha! 🎂",
    "Fun fact: Aapka birthday sirf aapka nahi, ek celebration hai jab aap duniya mein aaye the!",
    "Birthday cake pe candles daalna toh Greek culture ka part hai, bohot purani tradition hai!",
    "India mein cake cutting ceremony bohot famous hai, especially family aur friends ke saath!",
    "Birthday party sabke favourite hote hain, especially jab cake ho aur doston ke saath ho!",
    "Kuch jagah par &lsquo;birthday girl/boy&rsquo; likhi hui sash pehenti hain, taaki sabko pata chale!",
    "Fun Fact: India mein birthday ke din, kuch log apne saathiyon ko mithai ya snacks treat karte hain!",
    "India mein birthday ko special banane ke liye temple mein jaane ki bhi ek purani riwaaz hai!",
    "Did you know? India mein birthday par friends aur family saath mein milkar celebration karte hain!",
    "Fun Fact: Kuch jagah par birthday ke din, log &lsquo;pooja&rsquo; karte hain aur apne life ko safalta se bhare ka prarthna karte hain!",
    "Mithai aur snacks ke saath, birthday parties mein dance aur music ka bhi major role hota hai!",
    "India mein birthday par apne doston ko gifts dena ek important tradition hai!",
    "Did you know? Kuch regions mein birthday ko &lsquo;purna din&rsquo; mana kar, apne acche kaam shuru karte hain!",
    "Family ke saath birthday ka celebration zyada special hota hai, kyunki sab ek saath hote hain!",
    "Aapke birthday par family se blessings lena, ek bahut hi important ritual hai!",
    "India mein birthday pe &lsquo;chhoti si puja&rsquo; karna bhi ek common practice hai!",
    "Aapne suna hai? Kuch jagah par birthday wale din &lsquo;haldi&rsquo; ya &lsquo;kumkum&rsquo; bhi diya jata hai, taaki saara saal khush rahe!"
  ];