export const wishes = [
    "Aapko ek aur year full of laughter, joy aur unforgettable memories mile. May all your dreams come true! 🎉",
    "Ek aur saal badha ho gaya, par wisdom zyada nahi aayi! Have an amazing year ahead!",
    "Happy birthday to the one who makes every moment better. Enjoy your special day! 🎂",
    "Yeh saal bhi adventures aur achievements se bhara ho. You got this!",
    "Is saal ke har din mein apne dreams ko chase karna. Keep shining and being amazing! ✨",
    "Khushiyan ho aapke saath, dosti ho, aur duniya ho aapke kadmo mein. Happy Birthday! 🌟",
    "Har saal aapke saath khushiyan hi khushiyan ho. Happy Birthday!",
    "May this special day bring loads of happiness aur endless joy to your life!",
    "Dil se wish karte hain, aapka har din special ho! Happy Birthday! 🎉",
    "Aapka birthday ho, aur aap khush na ho! Impossible! Enjoy the day! 🎈",
    "Let the celebrations begin with full energy! Wishing you the happiest of birthdays!",
    "May this year bring new opportunities aur beautiful memories jo life ko aur special banaye!",
    "Aapki zindagi ki har subah ho khushiyon se bhari, aur har raat ho sweet dreams. Happy Birthday!",
    "Cheers to another year of being fabulous! Rock the day ahead! 💃🕺",
    "May you always smile, laugh, aur keep shining bright like the star you are! ✨",
    "Aapke life ka har din, aapka birthday ho. Have a blast! 🎂",
    "Wishing you good health, love, aur success in all your endeavors this year. Happy Birthday!",
    "Kahi se bhi aapko shubhkamnaayein mil rahi ho, hamari taraf se bhi bohot saari wishes!",
    "Aapke sapne sach ho, aur aapki duniya bhi roshan ho. Happy Birthday!",
    "Tere janam din pe duniya ki saari khushiyan tujhse milne aaye! 🎉",
    "Wishing you endless laughter, love, and peace today and always!",
    "Aapka har pal ho doston se ghira, aur dosti ho duniya ki sabse khaas cheez!",
    "Ek aur saal ho gaya, par aap abhi bhi bilkul young aur fresh ho! Happy Birthday!",
    "May this birthday bring you success aur happiness jo aap deserve karte ho!",
    "Har din ko apne special din jaisa mehsoos karo. Happy Birthday! 🎁",
    "Tere jese friend sabko mile, aur har din naye adventures ho! Happy Birthday!",
    "Bari bari se wishes aur bohot si pyaar ki baatein, Happy Birthday! 🎂",
    "Dil se wish karte hain aapko, khushiyan aapke paas ho, har din aapka ho!",
    "Aap jahan bhi jayein, khushiyan hi khushiyan leke jayein. Happy Birthday!",
    "Every day is a good day when you&rsquo;re around. Have a super special birthday!",
    "Aapka har pal pyara ho, aur har pal sukhad ho. Happy Birthday!",
    "Duniya ki saari khushiyan mile, aur yeh saal ho aapka sabse accha saal!",
    "Aapke jeene ka tareeka sabko inspire kare. Happy Birthday!"
  ];